### ISSUE TITLE
Serviços Home

### ISSUE THREAD

**Issue by lucapcf** [IDEjr/site-relabjr-dev#20]
### OBS.:
- Criar 1 componente que será chamado n vezes com argumentos para "campos *"

## Desktop

- [x] imagem*
- [x] moldura
- [x] grid
- [ ] formatação

## Mobile

- [x] imagem*
- [x] moldura
- [x] grid
- [ ] formatação

**Comment by tomaee** [comment]
olhar a seta e quadrado
e imagem e texto receberem argumentos do netlify
e pra celular
